js:
  dest: ./assets/js
  vendor:
    paths: 
      - ./node_modules/foundation-sites/dist/js/foundation.js
    filename: vendor.bundle.js
  commons:
    modules: []
    filename: commons.bundle.js
  bundle:
    entries: ./src/js/bundle.js
    filename: bundle.js

css:
  dest: ./assets/css
  sass:
    src: ./src/scss/theme.scss
    includePaths:
      - ./node_modules
      - ./node_modules/foundation-sites/scss
  autoprefixer:
    browsers:
      - last 2 versions
    cascade: false

browsersync:
  proxy: localhost
  notify: false
  open: false
  snippetOptions:
    ignorePaths: "wp-admin/**"
